<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageIcon>ChatGPT Image 19 de abr. de 2025, 03_22_41.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialSkin.2" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\Downloads\ChatGPT Image 19 de abr. de 2025, 03_22_41.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HidSharp" Version="2.1.0" />
    <PackageReference Include="LibUsbDotNet" Version="2.2.75" />
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
    <PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
  </ItemGroup>

</Project>